package com.brandon3055.tolkientweaks;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;
import cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper;

import java.util.Arrays;

@Mod(modid = TolkienTweaks.MODID, name = TolkienTweaks.MODNAME,version = TolkienTweaks.VERSION, dependencies = "required-after:lotr;required-after:Railcraft")
public class TolkienTweaks
{
    public static final String MODID = "TolkienTweaks";
	public static final String MODNAME = "Tolkien Tweaks";
    public static final String RPREFIX = MODID.toLowerCase() + ":";
    public static final String VERSION = "build-14";

	public static final String networkChannelName = "TTweaksNC";
	public static SimpleNetworkWrapper network;

	@Mod.Instance(MODID)
    public static TolkienTweaks instance;

    @SidedProxy(clientSide = "com.brandon3055.tolkientweaks.client.ClientProxy", serverSide = "com.brandon3055.tolkientweaks.CommonProxy")
    public static CommonProxy proxy;

	@EventHandler
	public void serverLoad(FMLServerStartingEvent event)
	{
		//CommandHandler.init(event);
	}

    @EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
        ConfigHandler.init(event.getSuggestedConfigurationFile());

        event.getModMetadata().autogenerated = false;
        event.getModMetadata().credits = "GreatOrator (Requested all features in this mod)";
        event.getModMetadata().description = "This is a small mod that adds some additional features requested by GreatOrator to the TolkienCraft mod pack";
        event.getModMetadata().authorList = Arrays.asList("brandon3055");
        event.getModMetadata().logoFile = "";
        event.getModMetadata().url = "http://www.tolkiencraft.com/";
        event.getModMetadata().version = VERSION + "-MC1.7.10";

        ModItems.init();
        ModBlocks.init();
        proxy.registerRendering();
        proxy.registerEntities();
        proxy.registerTileEntities();
		proxy.initializeNetwork();
    }
    
    @EventHandler
    public void init(FMLInitializationEvent event) {proxy.registerListeners();}
}
