package com.brandon3055.tolkientweaks;

import com.brandon3055.brandonscore.handlers.FileHandler;
import com.brandon3055.brandonscore.registry.ModFeatureParser;
import com.brandon3055.tolkientweaks.client.gui.GuiHandler;
import com.brandon3055.tolkientweaks.command.CommandMilestone;
import com.brandon3055.tolkientweaks.command.CommandMilestoneConfig;
import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper;

import java.io.File;
import java.util.Collections;

@Mod(modid = TolkienTweaks.MODID, name = TolkienTweaks.MODNAME,version = TolkienTweaks.VERSION, dependencies = "required-after:draconicevolution;required-after:brandonscore")//;required-after:lotr;required-after:Railcraft")
public class TolkienTweaks
{
    public static final String MODID = "tolkientweaks";
	public static final String MODNAME = "Tolkien Tweaks";
    public static final String RPREFIX = MODID + ":";
    public static final String VERSION = "${mod_version}";

	public static final String networkChannelName = "TTweaksNC";
	public static SimpleNetworkWrapper network;

	@Mod.Instance(MODID)
    public static TolkienTweaks instance;

    @SidedProxy(clientSide = "com.brandon3055.tolkientweaks.client.ClientProxy", serverSide = "com.brandon3055.tolkientweaks.CommonProxy")
    public static CommonProxy proxy;

    public static Configuration configuration;

	@Mod.EventHandler
	public void serverLoad(FMLServerStartingEvent event) {
        event.registerServerCommand(new CommandMilestoneConfig());
        event.registerServerCommand(new CommandMilestone());
	}

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        configuration = new Configuration(new File(FileHandler.brandon3055Folder, "TolkienTweaks.cfg"));
        ConfigHandler.init(configuration);
        ModFeatureParser.registerModFeatures(MODID);

        event.getModMetadata().autogenerated = false;
        event.getModMetadata().credits = "GreatOrator (Requested all features in this mod)";
        event.getModMetadata().description = "This is a small mod that adds some additional features requested by GreatOrator to the TolkienCraft mod pack";
        event.getModMetadata().authorList = Collections.singletonList("brandon3055");
        event.getModMetadata().logoFile = "";
        event.getModMetadata().url = "http://www.tolkiencraft.com/";
        event.getModMetadata().version = VERSION + "-MC1.10.2";

        proxy.preInit(event);
    }
    
    @Mod.EventHandler
    public void init(FMLInitializationEvent event) {
        proxy.init();
		new GuiHandler();
	}
}
